### ISSUE TITLE
DiskSpace.ps1 failing

### ISSUE THREAD

**Issue by amtwo** [sqlcollaborative/dbareports#8]
When I run the DiskSpace collection on my standalone server, It fails to insert into the database (screenshot below).

The error message logged in the error log is:

```
PS>TerminatingError(): "Exception calling "ExecuteNonQuery" with "0" argument(s): "Cannot insert the value NULL into column 'ServerID', table '@TVP'; column does not allow nulls. INSERT fails.
The data for table-valued parameter "@TVP" doesn't conform to the table type of the parameter.
The statement has been terminated.""

```

For some reason, the ServerID isn't being picked up, and thus it attempts to insert NULL for the ServerID. This is confirmed when looking at the console output, which shows blank values for ServerID.

![image](https://cloud.githubusercontent.com/assets/9381581/17877996/95479d16-68b5-11e6-805c-1d84eea5e07a.png)

**Comment by SQLDBAWithABeard** [comment]
Hmm, this was fixed by this commit 7521dad541c71781a353df221ce87dbf84bcd212 - Please can you try with the latest code and see if it is replicated still and report back

**Comment by amtwo** [comment]
Uninstalled, re-installed, and still having this issue.
Confirmed that this specific commit is included on my files (so, I'm not crazy, I don't think).

In DiskSpace.ps1, line 61 is this:
    $servers = Get-Instances

If I inspect `$servers`, it looks like ServerID is null. 
    $servers | Select ServerId, ServerName
![image](https://cloud.githubusercontent.com/assets/9381581/17953861/e834018c-6a44-11e6-839b-7c7144d3ff8e.png)


If I grab the query from Get-Instances and run it in SSMS, it returns a value for ServerID:
![image](https://cloud.githubusercontent.com/assets/9381581/17954056/4e819dc2-6a46-11e6-92aa-59acb9cbb279.png)

I have no idea why this isn't working...I have this on an Azure VM. I'm happy to ping you in the AM and get you access to the VM if you want to be hands-on to replicate the problem.

**Comment by PsPsam** [comment]
Changing line 79 $serverID = $server.ServerID to $serverID = $server.InstanceID works better
![image](https://cloud.githubusercontent.com/assets/20344934/17962871/285886a2-6ab3-11e6-84a5-01c656e05fd9.png)

Now I get another error

Attempting Import of 283 row(s)
PS C:\DbaReports> TerminatingError(): "Exception calling "ExecuteNonQuery" with "0" argument(s): "Error converting data type nvarchar to numeric.
The data for table-valued parameter "@TVP" doesn't conform to the table type of the parameter. SQL Server error is: 8114, state: 5
The statement has been terminated.""
WARNING: See error log C:\DbaReports\logs\dbareports-exceptions.txt for more details.
Bulk insert failed. Recording exception and quitting.
Finished

**Comment by PsPsam** [comment]
I have the script DiskSpace Working Whoohoo :)

One problem is that Initialize-database returns Capacity, FreeSpace and Percantage as String. When It tries to add back with decimal and integer it craps out.

I have added the below lines in begin block

![image](https://cloud.githubusercontent.com/assets/20344934/17965708/333982aa-6abe-11e6-90b7-b21fda97ecbb.png)

I have added the below in Process block
![image](https://cloud.githubusercontent.com/assets/20344934/17965717/3fa8d5f4-6abe-11e6-9344-aab22dc2d704.png)

After these changes I have data in the table

**Comment by js0505** [comment]
You need to update lines 124 and 125
$total = "{0:f2}" -f ($disk.Capacity/1gb)
$free = "{0:f2}" -f ($disk.Freespace/1gb)
used to be 
$total = "{0:n2}" -f ($disk.Capacity/1gb)
$free = "{0:n2}" -f ($disk.Freespace/1gb)

**Comment by PsPsam** [comment]
Changed the script as js0505 said it should be doesn't get the error as before but now get the following error

C:\DbaReports\shared.ps1
At C:\DbaReports\shared.ps1:536 char:2
+     $cmd.ExecuteNonQuery()
+     ~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "0" argument(s): "Arithmetic overflow error converting nvarchar to data type numeric.
The data for table-valued parameter "@TVP" doesn't conform to the table type of the parameter. SQL Server error is: 8115, state: 8
The statement has been terminated." ---> System.Data.SqlClient.SqlException: Arithmetic overflow error converting nvarchar to data type numeric.
The data for table-valued parameter "@TVP" doesn't conform to the table type of the parameter. SQL Server error is: 8115, state: 8
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Going back to the solution I found :)

**Comment by js0505** [comment]
@PsPsam can you PM me your files from the output for DiskSpace?

**Comment by PsPsam** [comment]
$ServerName = $server.ServerName
		$ServerId = $server.ServerId 
		$date = Get-Date

Need to be 
		$ServerName = $server.ServerName
		$ServerId = $server.InstanceId
		$date = Get-Date

**Comment by SQLDBAWithABeard** [comment]
Hi @PsPsam we have to use ServerID for the diskspace otherwise we would have multiple entries for diskspace on a server with multiple instances. 

What are the contents of your ServerInfo table? Has that been populated successfully?

Regards

Rob

**Comment by SQLDBAWithABeard** [comment]
resolved in latest release
